name: Build

on:
  workflow_call:
    outputs:
      pre-release:
        value: ${{ jobs.build.outputs.pre-release }}
      version: 
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      # convert PublicRelease to a boolean by comparing the string value to 'true'
      pre-release: ${{ steps.relInfo.outputs.preRelease != 0 }}
      version: ${{ steps.relInfo.outputs.extensionVersion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0 # fetch-depth 0 needed for NBGV
      - name: Nerdbank.GitVersioning
        uses: dotnet/nbgv@v0.4.2
        id: nbgv
      - name: Install Dependencies
        run: npm ci
      - name: Calculate Release Info
        id: relInfo
        uses: actions/github-script@v6.0.0
        env:
          SEM_VER_2_VERSION: ${{ steps.nbgv.outputs.SemVer2 }}
          SIMPLE_VERSION: ${{ steps.nbgv.outputs.SimpleVersion }}
        with:
          script: |
            const { SEM_VER_2_VERSION, SIMPLE_VERSION } = process.env;

            const onDevelopBranch = context.ref === 'refs/heads/develop';
            const onReleaseBranch = context.ref.startsWith('refs/heads/release/');
            const onPublicationBranch = onDevelopBranch || onReleaseBranch;

            const preRelease = onDevelopBranch ? true : false;
            const extensionVersion = onPublicationBranch ? SIMPLE_VERSION : SEM_VER_2_VERSION;

            // convert boolean preRelease value to integer via + operator for github expressions compatibility
            core.setOutput('preRelease', +preRelease);
            core.setOutput('extensionVersion', extensionVersion);

      - name: Pack Extension
        if: ${{ steps.relInfo.outputs.preRelease == '0' }}
        run: npx vsce pack ${{ steps.relInfo.outputs.extensionVersion }} --no-git-tag-version 
      - name: Pack Pre-Release Extension
        if: ${{ steps.relInfo.outputs.preRelease }} != 0
        run: npx vsce pack ${{ steps.relInfo.outputs.extensionVersion }} --no-git-tag-version --pre-release  
      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4.3.0
        with: 
          name: Extension
          path: dbos-ttdbg*.vsix