name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize

jobs:
  build:
    uses: ./.github/workflows/build.yml
